openapi: 3.0.0
info:
  version: 1.0.0
  title: Rest API Starter Explorer
  description: A proposed openAPI explorer for Rest Api Starter Template
schemes:
  - http
servers:
  - url: http://localhost:3000/api/v1
    description: Development server
tags:
  - name: auth
    description: Authentication and authorization operations
  - name: user
    description: Operations about user
paths:
  /auth/register:
    post:
      tags:
        - auth
      summary: Creates a new User
      description: Creates a new user
      consumes:
        - application/json
      produces:
        - application/json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  required: true
                  example: user@email.com
                password:
                  type: string
                  example: Password@123
      responses:
        '201':
          description: User Created successfully.
        '400':
          description: Unable to create user.
  /auth/login:
    post:
      tags:
        - auth
      summary: Login a user
      description: Login a user using email and password.
      consumes:
        - application/json
      produces:
        - application/json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  required: true
                  example: user@email.com
                password:
                  type: string
                  example: Password@123
      responses:
        '200':
          description: Logged In Successfully.
        '400':
          description: Unable to Login.
  /auth/token/verify:
    get:
      tags:
        - auth
      summary: Verifies a given token for a new user
      description: Verifies a token for a new user
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: t
          schema:
            type: string
          description: Access token
      responses:
        '200':
          description: Token Verified successfully.
        '400':
          description: Failed to verify the token.
  /auth/token/resend:
    post:
      tags:
        - auth
      summary: Resend Token
      description: Resend Token for a new user
      consumes:
        - application/json
      produces:
        - application/json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  required: true
                  example: user@email.com
                password:
                  type: string
                  example: Password@123
      responses:
        '200':
          description: Token Resent Successfully.
        '400':
          description: Unable to Resend token.
        '401':
          description: Incorrect Password
  /auth/password:
    patch:
      tags:
        - auth
      summary: Change Password
      description: Change password using old password
      consumes:
        - application/json
      produces:
        - application/json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                oldPassword:
                  type: string
                  required: true
                  example: Password@123
                newPassword:
                  type: string
                  example: Password@124
      responses:
        '200':
          description: Password Changed Successfully.
        '400':
          description: Bad Request.
        '403':
          description: Password Change Failed Try Again later
      security:
        - bearerAuth: []
  /auth/password/reset/code/resend:
    post:
      tags:
        - auth
      summary: Regenerate code to reset password
      description: Regenerate OTP to reset password
      consumes:
        - application/json
      produces:
        - application/json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  required: true
                  example: user@email.com
      responses:
        '200':
          description: OTP Sent successfully to your email.
        '400':
          description: Failed, User doesn't exist.
  /auth/password/reset/code:
    post:
      tags:
        - auth
      summary: Generate code to reset password
      description: Generate OTP to reset password
      consumes:
        - application/json
      produces:
        - application/json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  required: true
                  example: user@email.com
      responses:
        '200':
          description: OTP Sent successfully to your email.
        '400':
          description: Failed, User doesn't exist.
  /auth/password/reset:
    post:
      tags:
        - auth
      summary: Reset password using OTP
      description: Reset password of a user using OTP.
      consumes:
        - application/json
      produces:
        - application/json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  required: true
                  example: user@email.com
                password:
                  type: string
                  required: true
                  example: password@123
                otp:
                  type: integer
                  required: true
      responses:
        '200':
          description: Password Reset successfully.
        '400':
          description: Failed, Check the error message for details.
  /auth:
    delete:
      tags:
        - auth
      summary: Delete a user permanently
      description: Deletes a user permanently.
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: Deleted Successfully.
        '400':
          description: Bad Request.
        '403':
          description: Failed to delete user
      security:
        - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT 